spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
  application:
    name: nut-party-bot

bot:
  enable-film-refresh: false
  films-refresh: ${FILMS_REFRESH_CRON}
  google:
    token: ${GOOGLE_TOKEN}
    spreadsheet-id: ${GOOGLE_SPREADSHEET_ID}
    tables: ${TABLES}
  tg:
    token: ${TG_BOT_TOKEN}

channels:
  admin: ${ADMIN_ID}
  groups: ${GROUPS_ID}

mongock:
  migration-scan-package:
    - ru.sultanyarov.nutpartybot.domain.migration
  transactionEnabled: false

book:
  places-count: ${PLACES_COUNT}

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers